language: java
sudo: required

jdk:
  - oraclejdk11
  - oraclejdk8

before_install:
  - wget -O - https://github.com/jphp-compiler/jphp/releases/download/jppm-0.6.6/jppm-setup-0.6.6.sh | bash

script:
  - jppm install
  - jppm test